version: '3.8'

services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: sail-8.2/app
        extra_hosts:
          - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:5173'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            PATH: '${PATH}'
        volumes:
            - '.:/var/www/html'
            - './docker/8.2/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'sail-laravel-storage:/var/www/html/storage'
        networks:
            - sail
        restart: unless-stopped

volumes:
    sail-laravel-storage:

networks:
    sail:
        driver: bridge
